# .golangci.yml
version: "2"

run:
  timeout: 5m
  build-tags:
    - cgo

linters:
  disable:
    - errcheck
  enable:
    - misspell
    - unconvert

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/MereWhiplash/engram-cogitator

exclusions:
  paths:
    - sqlite_nocgo\.go
