# .goreleaser.yaml
version: 2

project_name: engram-cogitator

before:
  hooks:
    - go mod tidy

builds:
  # Solo mode MCP server (CGO required for SQLite)
  # Only linux/amd64 - CGO cross-compilation doesn't work for other targets
  # Users on macOS/ARM should build from source: CGO_ENABLED=1 go build ./cmd/server
  - id: server
    main: ./cmd/server
    binary: ec-server
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}}

  # API server (no CGO)
  - id: api
    main: ./cmd/api
    binary: ec-api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

  # Shim (no CGO)
  - id: shim
    main: ./cmd/shim
    binary: ec-shim
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: server
    ids:
      - server
    name_template: "ec-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

  - id: shim
    ids:
      - shim
    name_template: "ec-shim_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: MereWhiplash
    name: engram-cogitator
  prerelease: auto
  draft: false
